###����˿ں�
server:
    port: 8100
###eureka ������Ϣ����
eureka:
    instance:
        ###ע�ᵽeurekaip��ַ
        hostname: 127.0.0.1
    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
        ###��Ϊ�Լ���Ϊע�����ģ�����Ҫ�Լ�ע���Լ�
        register-with-eureka: false
        ###��Ϊ�Լ���Ϊע�����ģ�����Ҫ��������
        fetch-registry: false
